name:    web-boilerplate-haskell
version: "0.0.0"

dependencies:

# Due to a bug in GHC 8.0.1, we block its usage
# See: https://ghc.haskell.org/trac/ghc/ticket/12130
- base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5
#- base >=4.8.2.0 && <4.9

- yesod >=1.6 && <1.7
- yesod-core >=1.6 && <1.7
- yesod-auth >=1.6 && <1.7
- yesod-static >=1.6 && <1.7
- yesod-form >=1.6 && <1.7
- classy-prelude >=1.4 && <1.5
- classy-prelude-conduit >=1.4 && <1.5
- classy-prelude-yesod >=1.4 && <1.5
- bytestring >=0.9 && <0.11
- text >=0.11 && <2.0
- persistent >=2.8 && <2.9
# persistent-sqlite >=2.8 && <2.9
- persistent-postgresql >=2.8 && <2.11
- persistent-template >=2.5 && <2.9
- template-haskell
- shakespeare >=2.0 && <2.1
- hjsmin >=0.1 && <0.3
- monad-control >=0.3 && <1.1
- wai-extra >=3.0 && <3.1
- wai-cors
- yaml >=0.8 && <0.9
- http-client-tls >=0.3 && <0.4
- http-conduit >=2.3 && <2.4
- directory >=1.1 && <1.4
- warp >=3.0 && <3.3
#- data-default
#- aeson >=0.6 && <1.4
- aeson

- conduit >=1.0 && <2.0
- monad-logger >=0.3 && <0.4
- fast-logger >=2.2 && <2.5
- wai-logger >=2.2 && <2.4
- file-embed
- safe
- filepath
- time
- unordered-containers
- containers
- vector
- case-insensitive
- wai
- foreign-store
- jwt
- random
- hspec
# - soap >=0.2.2 && <0.3
# - iconv
- xml-conduit<1.9.0.0
- xml-conduit-writer
# - xml-conduit-parse
#- http-client-tls
- http-client
- tls
- connection
# - soap-tls
- x509-store
# - data-default-class
- x509-system
- x509-validation 
# - data-default
- x509
- configurator
- blaze-html
- mtl
# - data-default
- http-client
- tls == 1.5.8
- connection
- x509-store
# - data-default-class
- x509-system
- x509-validation 
# - data-default
- x509
- pem
- configurator
- xml-types
- utf8-string
- unicode-show
- unbounded-delays
- text
- random
#- time >= 1.8.0.2
- string-conversions
- libxml
- directory
- c14n
- cryptohash
- base64-bytestring
- RSA
#- crypto-pubkey-openssh
- crypto-pubkey-types
- HsOpenSSL
- mtl
- transformers
# - pkcs
- rio
#- hexstring
- cryptonite
- cryptostore
# process
# - xml-enumerator
#- regex-pcre
- split
#- http-client
#- soap-tls
- soap
- libxml
#- iconv
- resourcet
#- conduit
- stringsearch
- array
# entropy
# - DRBG
- uuid
- pkcs10
- HaXml
- pretty
- data-default-extra
- JuicyPixels
#pretty-1.1.3.6:
#- derive
#- DrIFT
# - crypto-api
- thumbnail
#- either >=4.1 && <5
- yesod-websockets
#- pdftotext
- pdf-toolbox-document
#- regex-compat
- regex-posix
- aeson-casing
- aeson-pretty
- jose
- lens
- regex-compat
- pdf-toolbox-core
- io-streams
- regex-tdfa
- pretty-simple
#- xml-prettify-text
- record-dot-preprocessor
- record-hasfield
- base16-bytestring
- process
- lucid
- strict-io
- wai-app-static
- profunctors
- folds
- casing
- xml-prettify-text
- pretty-simple
- stm
- with-utf8
#- cryptohash-sha1
#- regex-tdfa
#- regex-tdfa-text
# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

# Runnable executable for our application
executables:
  web-boilerplate-haskell:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - web-boilerplate-haskell
    when:
    - condition: flag(library-only)
      buildable: false

# Test suite
tests:
  web-boilerplate-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - web-boilerplate-haskell
    - hspec >=2.0.0
    - yesod-test
    - microlens

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
